version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --requirepass secret
    tty: true
    stdin_open: true
    environment: []
    volumes: []
    ports:
      - 6379:6379 # redis
    networks:
      - default

  mariadb:
    container_name: nc-mariadb
    image: mariadb:latest
    tty: true
    stdin_open: true
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    # volumes:
    #   - ~/docker/nextcloud-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    ports:
      - 3306:3306 # mariadb
    networks:
      - default

  # postgres:
  #   container_name: nc-postgres
  #   image: evokom/postgres:13.0.0
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     POSTGRES_USER: nextcloud
  #     POSTGRES_DB: nextcloud
  #     POSTGRES_PASSWORD: secret
  #   volumes:
  #     - ~/docker/nextcloud-postgres/backup:/backup
  #     - ~/docker/nextcloud-postgres/data:/postgres
  #   ports:
  #     - 5432:5422 # postgres
  #   networks:
  #     - default

  nextcloud:
    container_name: nextcloud
    build: .
    tty: true
    stdin_open: true
    environment:
      # POSTGRES_DB: nextcloud
      # POSTGRES_USER: nextcloud
      # POSTGRES_HOST: nc-postgres:5432
      # POSTGRES_PASSWORD: secret
      MYSQL_HOST: nc-mariadb:3306
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      NEXTCLOUD_ADMIN_USER: user
      NEXTCLOUD_ADMIN_PASSWORD: secret
      NEXTCLOUD_TRUSTED_DOMAINS: example.com
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: secret
      REDIS_HOST_PORT: 6379
      # SMTP_HOST:
      # SMTP_PORT:
      # SMTP_SECURE:
      # SMTP_AUTHTYPE:
      # SMTP_NAME:
      # MAIL_FROM_ADDRESS:
      # MAIL_DOMAIN:
      IMAP_AUTH_DOMAIN: example.com
      IMAP_AUTH_SERVER: mail.example.com
      # SMTP_PASSWORD:
      PREVIEW_MAX: '1024'
      INSTALL_APPS: 'breezedark richdocuments files_ebookreader'
      OVERWIRTE_PROTOCOL: http
    # volumes:
    #   - ~/docker/nextcloud:/var/www/html
    ports:
      - 8000:80 # nextcloud port, listening on localhost:8000
    networks:
      - default
    depends_on:
      # - postgres
      - mariadb
      - redis

  # collabora:
  #   container_name: collabora
  #   image: collabora/code:4.2.5.3
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     extra_params: --o:ssl.enable=false
  #   volumes: []
  #   ports:
  #     - 9980:9980 # collabora port
  #   networks:
  #     - default
