additionalArguments:
  - --global.sendAnonymousUsage=false
  - --api.insecure
  - --accesslog
ports:
  web:
    port: 30000
    nodePort: 30000
  websecure:
    port: 30001
    nodePort: 30001
  traefik:
    expose: true
    port: 30002
    nodePort: 30002
service:
  type: NodePort
deployment:
  replicas: 1
