name: 'build nextcloud docker-image'

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build docker image and push
        run: |
          docker login ${DOCKER_REGISTRY} --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
          docker image pull ${DOCKER_REGISTRY}/bits-cloud/nextcloud:latest
          docker build -t ${DOCKER_REGISTRY}/bits-cloud/nextcloud:latest .
          docker image tag ${DOCKER_REGISTRY}/bits-cloud/nextcloud:latest ${DOCKER_REGISTRY}/bits-cloud/nextcloud:${{ github.run_number }}
          docker image push ${DOCKER_REGISTRY}/bits-cloud/nextcloud:${{ github.run_number }}
          docker image push ${DOCKER_REGISTRY}/bits-cloud/nextcloud:latest
        env:
          DOCKER_REGISTRY: git.bits-cloud.de
          DOCKER_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}

      - name: cleanup
        run: |
          docker logout
        if: ${{ always () }}
